name: Fantasy Sports Automation

on:
  schedule:
    - cron: '0 14 * * *'  # Runs every day at 9 AM Central
  workflow_dispatch:

jobs:
  run-fantasy-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install boto3
          pip install feedparser

      - name: Run Box Scores Scraper
        run: python mlb_box_scraper.py

      - name: Run Daily Rosters Scraper
        run: python mlb_daily_rosters_scraper.py

      - name: Run Weather Scraper
        run: python mlb_daily_weather_scraper.py

      - name: Run Season Stats Scraper
        run: python mlb_season_stats_scraper.py

      - name: Run Betting Odds Scraper
        run: python mlb_betting_odds_scraper.py

      - name: Run ESPN Articles Scraper
        run: python mlb_espn_articles_scraper.py

      - name: Run Probable Starters Scraper
        run: python mlb_probable_starters_scraper.py

      - name: Upload CSVs to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
        run: |
          aws s3 sync . s3://fantasy-sports-csvs/baseball/boxscores/ --exclude "*" --include "mlb_boxscores_*.csv"
          aws s3 sync . s3://fantasy-sports-csvs/baseball/rosters/ --exclude "*" --include "mlb_rosters_*.csv"
          aws s3 sync . s3://fantasy-sports-csvs/baseball/weather/ --exclude "*" --include "mlb_weather_*.csv"
          aws s3 sync . s3://fantasy-sports-csvs/baseball/seasonstats/ --exclude "*" --include "mlb_season_stats_*.csv"
          aws s3 sync . s3://fantasy-sports-csvs/baseball/betting/ --exclude "*" --include "mlb_betting_odds_*.csv"
          aws s3 sync . s3://fantasy-sports-csvs/baseball/news/ --exclude "*" --include "mlb_news_*.csv"
          aws s3 sync . s3://fantasy-sports-csvs/baseball/starters/ --exclude "*" --include "mlb_probable_starters_*.csv"
