name: Fantasy Sports Automation

on:
  schedule:
    - cron: '0 14 * * *'  # Runs daily at 9 AM Central (2 PM UTC)
  workflow_dispatch:

jobs:
  run-fantasy-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Box Scores Scraper
        run: |
          python mlb_box_scraper.py
          ls -la  # ✅ Check if CSV created

      - name: Run Daily Rosters Scraper
        run: |
          python mlb_daily_rosters_scraper.py
          ls -la  # ✅ Check if CSV created

      - name: Run Weather Scraper
        run: |
          python mlb_daily_weather_scraper.py
          ls -la  # ✅ Check if CSV created

      - name: Run Season Stats Scraper
        run: |
          python mlb_season_stats_scraper.py
          ls -la  # ✅ Check if CSV created

      - name: Upload CSV Outputs
        uses: actions/upload-artifact@v4
        with:
          name: fantasy-csv-outputs
          path: |
            mlb_boxscores_*.csv
            mlb_rosters_*.csv
            mlb_weather_*.csv
            mlb_season_stats_*.csv

      - name: Commit and Push CSV Files
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add *.csv
          git status   # ✅ Show what’s staged
          git commit -m "Add updated CSV files" || echo "No changes to commit"
          git push https://x-access-token:${TOKEN}@github.com/brandoncoates/fantasy-sports-automation.git HEAD:main
