name: Daily Fantasy Scrapers

on:
  schedule:
    - cron: '14 14 * * *'  # Runs daily at 9:14 AM Central (14:14 UTC)
  workflow_dispatch:

jobs:
  run-fantasy-scripts:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-2
      S3_BUCKET_NAME: fantasy-sports-csvs

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests beautifulsoup4 awscli

      ##########################################
      # ✅ Run All Scrapers (Grouped by Type)
      ##########################################

      # Daily Box Scores
      - name: Run Box Score Scraper
        run: python mlb_box_scraper.py

      # Daily Rosters
      - name: Run Roster Scraper
        run: python mlb_daily_rosters_scraper.py

      # Daily Weather
      - name: Run Weather Scraper
        run: python mlb_daily_weather_scraper.py

      # Probable Starters
      - name: Run Probable Starters Scraper
        run: python mlb_probable_starters_scraper.py

      # Betting Odds
      - name: Run Betting Odds Scraper
        run: python mlb_betting_odds_scraper.py

      # ESPN News
      - name: Run ESPN Articles Scraper
        run: python mlb_espn_articles_scraper.py

      # Player Props & Projections
      - name: Run DraftKings player props
        run: python mlb_draftkings_player_props.py

      - name: Run ESPN player projections
        run: python mlb_espn_player_projections.py

      - name: Run Rotogrinders DraftKings projections
        run: python mlb_rotogrinders_draftkings_projections.py

      - name: Run Rotogrinders FanDuel projections
        run: python mlb_rotogrinders_fanduel_projections.py

      # Player Salaries
      - name: Run DraftKings salaries scraper
        run: python "Fantasy Baseball/MLB Player Salaries/mlb_draftkings_salaries.py"

      - name: Run FanDuel salaries scraper
        run: python "Fantasy Baseball/MLB Player Salaries/mlb_fanduel_salaries.py"

      ##########################################
      # ✅ Upload All CSVs to Correct S3 Paths
      ##########################################

      - name: Upload all CSVs to S3
        run: |
          TODAY=$(date +%Y-%m-%d)

          # Box Scores
          aws s3 cp "mlb_boxscores_${TODAY}.csv" s3://$S3_BUCKET_NAME/baseball/boxscores/ --acl public-read

          # Rosters
          aws s3 cp "mlb_rosters_${TODAY}.csv" s3://$S3_BUCKET_NAME/baseball/rosters/ --acl public-read

          # Weather
          aws s3 cp "mlb_weather_${TODAY}.csv" s3://$S3_BUCKET_NAME/baseball/weather/ --acl public-read

          # Starters
          aws s3 cp "mlb_probable_starters_${TODAY}.csv" s3://$S3_BUCKET_NAME/baseball/starters/ --acl public-read

          # Betting Odds
          aws s3 cp "mlb_betting_odds_${TODAY}.csv" s3://$S3_BUCKET_NAME/baseball/betting/ --acl public-read

          # ESPN News
          aws s3 cp "mlb_espn_articles_${TODAY}.csv" s3://$S3_BUCKET_NAME/baseball/news/ --acl public-read

          # Player Projections and Props
          aws s3 cp "mlb_draftkings_player_props_${TODAY}.csv"   s3://$S3_BUCKET_NAME/baseball/playerprojections/draftkings/       --acl public-read
          aws s3 cp "mlb_espn_player_projections_${TODAY}.csv"   s3://$S3_BUCKET_NAME/baseball/playerprojections/espn/            --acl public-read
          aws s3 cp "mlb_rotogrinders_dk_${TODAY}.csv"           s3://$S3_BUCKET_NAME/baseball/playerprojections/rotogrinders_dk/ --acl public-read
          aws s3 cp "mlb_rotogrinders_fd_${TODAY}.csv"           s3://$S3_BUCKET_NAME/baseball/playerprojections/rotogrinders_fd/ --acl public-read

          # Player Salaries
          aws s3 cp "Fantasy Baseball/MLB Player Salaries/mlb_draftkings_salaries_${TODAY}.csv" s3://$S3_BUCKET_NAME/baseball/playersalaries/draftkings/ --acl public-read
          aws s3 cp "Fantasy Baseball/MLB Player Salaries/mlb_fanduel_salaries_${TODAY}.csv"    s3://$S3_BUCKET_NAME/baseball/playersalaries/fanduel/    --acl public-read
