name: Run FTA DK Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "15 14 * * *"  # Runs daily at 9:15am Central

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas beautifulsoup4 lxml requests

      - name: Run scraper
        run: python mlb_fta_salaries_ownership_scraper.py

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3
        run: |
          today=$(date +%F)
          aws s3 cp mlb_fta_salaries_ownership_dk_$today.csv s3://fantasy-sports-csvs/baseball/ownership/mlb_fta_salaries_ownership_dk_$today.csv
