name: Run Rotogrinders Projections

on:
  schedule:
    - cron: '30 13 * * *'
  workflow_dispatch:

jobs:
  rotogrinders:
    runs-on: ubuntu-latest

    steps:
    - name: ⬇️ Checkout Repository
      uses: actions/checkout@v4

    - name: 🐍 Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 🎯 Run Rotogrinders Projections
      run: python mlb_rotogrinders_projections_scraper.py

    - name: ☁️ Upload CSVs to S3
      run: python upload_all_mlb_csvs.py
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
