name: Run DraftKings Salaries

on:
  schedule:
    - cron: '40 13 * * *'
  workflow_dispatch:

jobs:
  dk-salaries:
    runs-on: ubuntu-latest

    steps:
    - name: ⬇️ Checkout Repository
      uses: actions/checkout@v4

    - name: 🐍 Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 💵 Run DraftKings Salaries Scraper
      run: python mlb_draftkings_salaries.py

    - name: ☁️ Upload CSVs to S3
      run: python upload_all_mlb_csvs.py
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
