name: Run Rotowire Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '30 14 * * *'

jobs:
  scrape-rotowire:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pandas boto3 beautifulsoup4 selenium

    - name: Install Chrome v114 & Chromedriver v114
      run: |
        sudo apt remove -y google-chrome-stable || true
        wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_114.0.5735.90-1_amd64.deb
        sudo apt install -y ./google-chrome-stable_114.0.5735.90-1_amd64.deb

        wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Run Rotowire Salaries & Ownership Scraper
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
      run: python mlb_rotowire_salaries_ownership_scraper.py
