name: Run Rotowire Salaries & Ownership Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "30 14 * * *"  # Runs every day at 14:30 UTC (9:30 AM Central)

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Post Checkout repo
        uses: actions/checkout@v3

      - name: Post Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Chrome & Chromedriver 114
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget
          wget https://storage.googleapis.com/chrome-for-testing-public/114.0.5735.90/linux64/chrome-linux64.zip
          wget https://storage.googleapis.com/chrome-for-testing-public/114.0.5735.90/linux64/chromedriver-linux64.zip
          unzip chrome-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chrome-linux64 /opt/chrome
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo ln -sf /opt/chrome/chrome /usr/bin/google-chrome
          sudo ln -sf /opt/chrome/chrome /usr/bin/chromium-browser || true
          echo "Installed Chrome and Chromedriver 114"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4 pandas boto3

      - name: Run Rotowire Salaries & Ownership Scraper
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          python fantasy-sports-automation/fantasy-sports-automation/mlb_rotowire_salaries_ownership_scraper.py
