name: Run Rotowire MLB Player Props Scraper

on:
  schedule:
    - cron: '55 14 * * *'  # Runs daily at 9:55 AM Central
  workflow_dispatch:       # Manual trigger anytime

jobs:
  run-rotowire-props:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 beautifulsoup4 requests

      - name: Run Rotowire Props Scraper
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          python mlb_rotowire_player_props_scraper.py
