name: Run Rotowire Salaries & Ownership Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "30 14 * * *"  # 9:30 AM Central Time

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip google-chrome-stable

      - name: Install matching ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          echo "Chrome version: $CHROME_VERSION"
          wget -q https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION -O chromedriver_version.txt || echo "Can't find exact match, using major.minor"
          if [ ! -s chromedriver_version.txt ]; then
            echo "Fetching fallback chromedriver version for major.minor"
            CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+')
            wget -q https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION -O chromedriver_version.txt || echo "Fallback wget failed too, continuing..."
          fi
          CHROMEDRIVER_VERSION=$(cat chromedriver_version.txt)
          echo "ChromeDriver version: $CHROMEDRIVER_VERSION"
          wget -q https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4 pandas boto3

      - name: Run Rotowire Salaries & Ownership Scraper
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-2"
        run: |
          python fantasy-sports-automation/mlb_rotowire_salaries_ownership_scraper.py
