name: scrape-rotowire

on:
  workflow_dispatch:
  schedule:
    - cron: '30 14 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install pandas boto3 beautifulsoup4 selenium

    - name: Install Chromium & Chromedriver 114
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver
        echo "✅ Installed Chromium and Chromedriver 114"

    - name: Run Rotowire Salaries & Ownership Scraper
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
      run: python mlb_rotowire_salaries_ownership_scraper.py
