name: Run Rotowire Salaries & Ownership Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'  # Runs daily at 9 AM Central

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4 pandas boto3

      - name: Install Chrome & Chromedriver 138
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          
          # Install Chrome 138
          wget https://storage.googleapis.com/chrome-for-testing-public/138.0.7264.0/linux64/chrome-linux64.zip
          unzip chrome-linux64.zip
          sudo mv chrome-linux64 /opt/chrome
          sudo ln -s /opt/chrome/chrome /usr/bin/chromium-browser

          # Install ChromeDriver 138
          wget https://storage.googleapis.com/chrome-for-testing-public/138.0.7264.0/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Run Rotowire Salaries & Ownership Scraper
        run: python mlb_rotowire_salaries_ownership_scraper.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
